### ISSUE TITLE
更新最新版IDEA后无法使用插件，希望大佬修复一下

### ISSUE THREAD

**Issue by ebdmn** [ChenYilei2016/mysql2h2-plus#2]
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.1, WebStorm 2023.1)
不兼容，需要IDEA内核版本223.*或更低

**Comment by ChenYilei2016** [comment]
我升级下最新版试下 (⊙o⊙)…..

**Comment by ChenYilei2016** [comment]
github 已经更新, idea插件市场还在审核中

**Comment by ebdmn** [comment]
已经可以了，大佬辛苦了
